name: grassroots_app
description: Grassroots

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.0+1
  vector_graphics: ^1.0.1

  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6

  google_sign_in: ^5.4.4

  flutter_native_splash: ^2.2.17
  
  shared_preferences: ^2.0.17
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true

  android_gravity: center

  android_screen_orientation: portrait

  branding: assets/icons/branded-quoteless-transparent-cropped.png
  branding_dark: assets/icons/branded-quoteless-transparent-cropped.png

  branding_mode: bottom

  color: "#ffffff"
  color_dark: "#000000"

  fullscreen: true

  icon_background_color: "#ffffff"
  icon_background_color_dark: "#000000"

  image: assets/icons/splash_icon.png
  image_dark: assets/icons/splash_icon.png

  ios: false

  ios_content_mode: center

  web: false

  web_image_mode: center

  android_12:
    android_gravity: center

    branding: assets/icons/branded-quoteless-transparent-cropped.png
    branding_dark: assets/icons/branded-quoteless-transparent-cropped.png

    branding_mode: bottom

    color: "#ffffff"
    color_dark: "#000000"

    icon_background_color: "#ffffff"
    icon_background_color_dark: "#000000"

    image: assets/icons/splash_icon.png
    image_dark: assets/icons/splash_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
