name: Test Cases
on: [workflow_dispatch]
jobs:
  Flutter-Test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
