name: Test Cases
on: [push, workflow_dispatch]
jobs:
  Futter-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
