name: Test Cases
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
jobs:
  Flutter-Test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      
    - name: Checkout Flutter-action
      uses: subosito/flutter-action@v1
      
    - name: Run Tests
      run: flutter test
    
    - name: Merge Pull Request
      if: ${{ github.event.pull_request.merged == true && success() }}
      run: |
          git merge --no-ff --no-commit ${{ github.event.pull_request.head.ref }}
